### ISSUE TITLE
Could not find part.inp file when the Abaqus job is submitted. 

### ISSUE THREAD

**Issue by bhaskara-chintada** [RSNA-QIBA-US-SWS/QIBA-DigitalPhantoms#5]
Dear All, 

Thank you for sharing this code. 

When the Abaqus FEM simulation job (Foc30mmF2p0_E30k_T167.inp) is submitted, it is giving me the error "The following file(s) could not be located: part.inp",  

Where could I find the part.inp file ? I didn't find it in the this repository. 
or What should I incorporate in part.inp file to run this simulation?

Thanks.

**Comment by mlp6** [comment]
@qiangbo might be able to answer this question as he contributed the Abaqus content in this repository.

**Comment by bhaskara-chintada** [comment]
Dear @mlp6 , thank you for your response. I am still interested on this aspect and I have only access to Abaqus FEM simulation tool.  Dear @qiangbo, Could you please provide your comments ? Your leads in this aspect is very much appreciated.

**Comment by mlp6** [comment]
@bhaskara-chintada this is quite late, but we have located the file that has been missing.  This file is large (1.3 GB), but < 50 MB compressed, so I will be uploading the compressed version to the repository.

**Comment by bhaskara-chintada** [comment]
Dear @mlp6 thank you for sharing the missing file.
