### ISSUE TITLE
Issue with running Abaqus file

### ISSUE THREAD

**Issue by masud407** [RSNA-QIBA-US-SWS/QIBA-DigitalPhantoms#8]
Hello,

As I don't have LS DYNA, I tried to import Foc30mmF2p0_E30k_T167.inp file on Abaqus. Then I tried to run the file on ABAQUS and didn't import any other supporting files. Unfortunately, it shows an error after running for a while and could not identify a bunch of nodes. Can you please guide me on how to run the Abaqus files?

Also, I tried to import the LS-dyna file (qiba_elastic_pml.dyn) on LS-dyna, but it shows nothing.

**Comment by mlp6** [comment]
I do not have an ABAQUS license, so I cannot help you with the issues running there.  I have assigned this to @qiangbo who originally developed that model.

If you don't have LS-DYNA, then I do not understand how you imported something into LS-DYNA.

**Comment by masud407** [comment]
Dr. Palmeri,

Thanks for your response. I contacted another lab that has the license for LS DYNA and tried to run it there, but I could not import the model. Can it be any issues related to the version (latest vs old) of LS-DYNA?

Thanks.

**Comment by mlp6** [comment]
@masud407 the model works for me with the latest version of `ls-dyna`, and I don't see a reason why it should not work with any version.  My guess would be that there is a syntax issue on trying to run it.
