### ISSUE TITLE
KeyError:-lmlog while running abaqus file

### ISSUE THREAD

**Issue by masud407** [RSNA-QIBA-US-SWS/QIBA-DigitalPhantoms#9]
I was trying to run Parse3DNode.py file on abaqus and I am getting the following error:
Line 21 of Parse3DNode.py file

hNodeSet = odb.rootAssembly.instances[instance].nodeSets[nodeset]
KeyError: -lmlog

Any suggestions to resolve it?

**Comment by mlp6** [comment]
I did not write that script, but that error implies that the file the script is trying to operate on does not exist in the path that it is extracting from the command line arguments (hence the "key error" being raised).
